/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.ListaSimple;
import EDD.Preguntas;
import EDD.arbolBinario;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
/**
 *
 * @author Miguel
 */
public class Welcome extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        CargarArbol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenidos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        exit.setText("Salida");
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 120, -1));

        CargarArbol.setText("Cargar Arbol");
        CargarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArbolActionPerformed(evt);
            }
        });
        jPanel1.add(CargarArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArbolActionPerformed
        //Variable para almacenar la clave
        String clave="";
        //Crear un JFileChooser que permite seleccioanr el archivo
        JFileChooser fileChooser = new JFileChooser();
        //cuadro de dialogo
        fileChooser.setDialogTitle("Selecciona tu archivo JSON");
        
        //permite seleccionar cualquier tipo de archivo
        fileChooser.setAcceptAllFileFilterUsed(true);
        
        //obtiene lo que hizo el usario 
        int result = fileChooser.showOpenDialog(null);
        
        //verifica que sea un archivo 
        if (result == JFileChooser.APPROVE_OPTION) {
            //obtiene el archivo seleccionado 
            File file = fileChooser.getSelectedFile();

            //abre el archivo seleccionado
            try (FileReader reader = new FileReader(file)) {
                // Leer el archivo JSON con Gson
                Gson gson = new Gson();//crea el objeto Gson
                //convierte el contenido del Json a un JsonObject
                JsonObject jsonObject = gson.fromJson(reader, JsonObject.class);

                

                //Crear instancia del arbol
                arbolBinario arbol= new arbolBinario();
                
                //Aqui se obtienen las claves principales del Json
                for(String claveTemporal: jsonObject.keySet()){
                    //se asigna la clave temporal
                    clave=claveTemporal;
                    //imprime la clave
                    System.out.println("Clave temporal:"+clave);
                }
                //Se obtiene el array asociado a la clave
                JsonArray items=jsonObject.getAsJsonArray(clave);
                
                //recorre los elementos del array
                for (int i = 0; i < items.size(); i++) {
                    
                    /*como cada elemento es un objecto,recorremos sobre las 
                    claves del objeto del arbol(cada clave es el nombre de una especie),
                    la variable nombreArbol almacena temporalmente cada objeto y 
                    despues se para obtener el array de las  preguntas 
                    asociadas a esa especie(objeto)
                    */
                    JsonObject arbolJson = items.get(i).getAsJsonObject();
                    for (String nombreArbol : arbolJson.keySet()) {
                        JsonArray caminoArray = arbolJson.getAsJsonArray(nombreArbol);

                        // Crear camino como ListaSimple<Preguntas>
                        ListaSimple<Preguntas> camino = new ListaSimple<>();
                        
                        //recorremos las preguntas
                        for (int j = 0; j < caminoArray.size(); j++) {
                            //cada elemnto es una pregunta
                            JsonObject preguntaJson = caminoArray.get(j).getAsJsonObject();
                            //recorremos los nombre de las preguntas
                            for (String pregunta : preguntaJson.keySet()) {
                                //obtenemos la respuesta
                                boolean respuesta = preguntaJson.get(pregunta).getAsBoolean();
                                //insertamos pregunta y respuesta 
                                camino.InsertarFinal(new Preguntas(pregunta, respuesta));
                            }
                        }

                        //verifica si el camino esta vacio
                        if(camino.getSize()==0){
                        //System.out.println("camino vacio crear nodo hoja"+nombreArbol);
                        
                        //Al arbol se le pasa la especie y las preguntas
                        arbol.contruirArbol(nombreArbol, camino);
                        }else{
                            
                            ////Al arbol se le pasa la especie y las preguntas
                            arbol.contruirArbol(nombreArbol, camino);
                        }
                    }
                }
                //le muestra al usario que se construyo el arbol
                System.out.println("El arbol se construyo correctamente.");
                //se crea una nueva interfaz que se le pasa el arbol creado 
                Interfaz_clave interfaz=new Interfaz_clave(arbol);
                //se hace visible 
                interfaz.setVisible(true);
             //si ocurre cualquier error    
            } catch (Exception e) {
                System.out.println("Error al leer el archivo JSON: " + e.getMessage());
            }
            //si no selecciono ningun archivo
        } else {
            System.out.println("No se seleccionó ningún archivo.");
        }
        
    }//GEN-LAST:event_CargarArbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarArbol;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
